### ISSUE TITLE
[Enhancement]: implement a wait-for-hit (a la pickel/kobo)

### ISSUE THREAD

**Issue by pazos** [NiLuJe/FBInk#24]
I would like to see a wait-for-touch option in fbink (ie: the program does not return after writting to the screen. It waits until a touch event on screen or a timeout). 

@NiLuJe feel free to close this issue if you don't find it useful

**Comment by NiLuJe** [comment]
You'll probably have to roll your own, see https://github.com/shermp/go-kobo-input f.g. ;).

**Comment by NiLuJe** [comment]
To expand a bit: it strays a bit too far from the initial goal (which was, err, doing `eips` better).

Doing `pickel` better was never really part of the equation (despite pickel being terrible ;D).

The limited amount of touch input handling we have with button_scan was borne of an experiment, it's already tricky enough to make sure something as limited as that works more or less correctly everywhere (spoiler: it probably doesn't :D)... ;).

**Comment by pazos** [comment]
Yup, thanks for the feedback. I ended using FBInk as a library. Congratulations, what a library.

https://github.com/pazos/cervantes-safemode.

**Comment by NiLuJe** [comment]
:+1: :)
