### ISSUE TITLE
[Cervantes]: messages are upside down.

### ISSUE THREAD

**Issue by pazos** [NiLuJe/FBInk#25]
Hey! Something weird is happening w/ my device. I did notice it because I started to tinker with FBInk library and saw the weird rotation, so I tried with the console tool and found the same.

output of `FBInk v1.9.0-24-g4a29b0f for Cervantes [Minimalistic build]`.

```
./fbink hello
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 300 dpi
[FBInk] Variable fb info: 1448x1072, 16bpp @ rotation: 0 (Upright, 0°)
[FBInk] Enabled Kobo @ 16bpp boot rotation quirks (1448x1072 -> 1072x1448)
[FBInk] Fontsize set to 32x32 (IBM base glyph size: 8x8)
[FBInk] Line length: 33 cols, Page size: 45 rows
[FBInk] Vertical fit isn't perfect, shifting rows down by 4 pixels
[FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Printing string 'hello' @ column 0 + 0px, row 0 + 0px (overlay: N, no BG: N, no FG: N, inverted: N, flashing: N, centered: N, halfway: N, left padded: N, clear screen: N, font: 0, font scaling: x0)
[FBInk] OpenType support is disabled in this FBInk build!
```

Output of `FBInk v1.7.0 for Kobo [Minimalistic build]` (Version used on lastest KOReader)

```
./fbink hello
[FBInk] Couldn't find a Kobo version tag (not running on a Kobo?)!
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Variable fb info: 1448x1072, 16bpp @ rotation: 0 (Upright, 0°)
[FBInk] Enabled Kobo @ 16bpp fb rotation quirks (1448x1072 -> 1072x1448)
[FBInk] Fontsize set to 24x24 (IBM base glyph size: 8x8)
[FBInk] Line length: 44 cols, Page size: 60 rows
[FBInk] Vertical fit isn't perfect, shitfting rows by 4 pixels to the bottom
[FBInk] Fixed fb info: ID is "mxc_epdc_fb", length of fb mem: 6782976 bytes & line length: 2944 bytes
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Printing string 'hello' @ column 0 + 0px, row 0 + 0px (overlay: false, backgroundless: false, inverted: false, flashing: false, centered: false, left padded: false, clear screen: false, font: 0, font scaling: x0)
```

I can't find any difference in stdout (besides opentype support and the error finding a Kobo model on my Cervantes) but old build works fine and new build writes messages rotated 180º.

**Comment by NiLuJe** [comment]
The old build was applying a single rotation tweak universally regardless of the reported orientation, as long as the device was @ 16bpp.

The new build tries to handle the two possible orientations, and as such needs to know which is which.

I forgot to apply the default value on Cervantes, too, that should hopefully fix this.

I'm hoping that, unlike on Kobo (where the Aura HD, H2O, and possibly H2Or² are special snowflakes with inverted panels), there aren't devices with a different native rotation...

**Comment by NiLuJe** [comment]
Keep me posted if that didn't do the trick ;).

**Comment by NiLuJe** [comment]
Also took care of that spurious "OT disabled" warning ;).

**Comment by pazos** [comment]
@NiLuJe: thanks, it worked.

Cervantes related: I can't reproduce QBookApp hangs while clearing the screen with new versions, so that worked too :+1:

**Comment by NiLuJe** [comment]
Great, thanks for testing ;).

If I could bother you with another random test: does image and OpenType rendering work without any side-effects on QBookApp?

**Comment by pazos** [comment]
> does image and OpenType rendering work without any side-effects on QBookApp?

Image works fine. Didn't try opentype fonts but truetype works nice without hanging QBookApp:
 `fbink -t regular=/usr/lib/fonts/Cabin-Regular.ttf,size=20 -mMq "hello world"`

Slightly unrelated: I need fbgrab or some tool to make screenshots, could you please share your sources :p ??

**Comment by NiLuJe** [comment]
Fantastic, thanks for double-checking ;).

FBGrab is [over here](http://trac.ak-team.com/trac/browser/niluje/Configs/trunk/Kindle/Misc/FBGrab) ;).
AFAICT, it *should* behave out of the box (you'll just get the usual "I'm not on a Kobo, wah wah", warning ^^).
