### ISSUE TITLE
question regarding API for image centering.

### ISSUE THREAD

**Issue by pazos** [NiLuJe/FBInk#26]
Sorry for bother you again @NiLuJe.

I'm trying to print images to the screen using the library, but I'm unable to center the image on the screen. I set up halign and valign to CENTER in fbink_config, but no way.

I'm looking for something like `fbink -g file=/path/to/image,halign=CENTER,valign=CENTER -cf`

**Comment by NiLuJe** [comment]
That should be enough, yeah.

Is your WIP code up somewhere, so that I can take a look at it?

**Comment by NiLuJe** [comment]
And another stupid question: where does it currently end up being positioned?

**Comment by pazos** [comment]
sorry, I was mixing x/y offset with col/rows. It works perfectly, Just need to reset cols/rows just before calling fbink_print_image

**Comment by NiLuJe** [comment]
Yep, offsets are appended to row/col ;).
