### ISSUE TITLE
OT/TT Baseline mode (single line?)

### ISSUE THREAD

**Issue by shermp** [NiLuJe/FBInk#27]
So, I finally chanced upon (what became) the miniclock thread, and I was thinking a single line, baseline insert mode might be quite useful.

I envision the mode to use the left and right margin, with the insert point being the baseline, and only prints one line. The mode could also refresh the entire 'line' to ensure that there are no 'leftovers' when overwriting a line.

The baseline insertion would assist those who are looking to align the clock with the *page n of nn* text, for example.

Your thoughts?

**Comment by NiLuJe** [comment]
I get the idea, but I'm not sure if that would be any more user-friendly in this case.

If you go to the trouble of taking a snapshot and computing the baseline of an existing string from that, sure, but somehow I don't think anyone did? ^^.

Other than that, it certainly makes sense in theory, so, why not ;).
