### ISSUE TITLE
free_ot_font: Double Free

### ISSUE THREAD

**Issue by yparitcher** [NiLuJe/FBInk#36]
When calling `fbink_free_ot_fonts()` twice there is a double free.
for example:
```C
fbink_add_ot_font("font.ttf", FNT_REGULAR);
fbink_free_ot_fonts();
...
fbink_add_ot_font("font.ttf", FNT_REGULAR);
fbink_free_ot_fonts();
```
in a long running program.

https://github.com/NiLuJe/FBInk/blob/5642e16cd9859c9e815322f82626232396ecbdc5/fbink.c#L2720
only nulls the local copy of `font_info`
however the global pointer `otFonts.otRegular` is not nulled, which leaves a dangling pointer -> double free.

I am not sure how to pass the pointer to fix this.
Thanks

**Comment by NiLuJe** [comment]
Whoops.

Nice catch, and thanks for the PR, which I'll apply shortly, as that was the exact same thing I was going to try ;).
