### ISSUE TITLE
Option for -i, --img is referenced but undefined

### ISSUE THREAD

**Issue by fulldecent** [NiLuJe/FBInk#58]
The `-g`, `--image` option is defined at https://github.com/NiLuJe/FBInk/blob/master/fbink_cmd.c#L287

But in the examples, it is also mentioned of a `-i`, `--img` option at https://github.com/NiLuJe/FBInk/blob/master/fbink_cmd.c#L299 (and other places)

This `-i`, `--img` has no definition. 

Please define this in the documentation.

**Comment by NiLuJe** [comment]
It's a hack to bypass getsubopt limitations with forbidden token-like characters in the arguments. (i.e., `-i` == `-g:file`).

Not quite sure there's a sane way to deal with that besides the existing comments?

**Comment by NiLuJe** [comment]
(By which I mean https://github.com/NiLuJe/FBInk/blob/master/fbink_cmd.c#L316)
