### ISSUE TITLE
Specifying "-fPIC" CFLAG for static library

### ISSUE THREAD

**Issue by shermp** [NiLuJe/FBInk#7]
Hi @NiLuJe 

Would you be willing to add "-fPIC" as an optional CFLAG when compiling the static library? 

The reason is that CGo does not seem to like linking to a static build without that flag, unless specifying the "--static" argument in cgo, which in turn breaks linking to glibc.

I did it myself, but I figured you may want to consider it for the project as a whole.

Thanks

**Comment by NiLuJe** [comment]
Is -fPIC mandatory, or does -fpic does the job?

**Comment by NiLuJe** [comment]
I added a "pic" target that builds a PIC static library.

(Because not a huge fan of suffering the performance implications of PIC unilaterally :/).

**Comment by NiLuJe** [comment]
Random thought: given the size of the library, it appears to have been stripped.

I imagine you're aware of the current mess that is [https://sourceware.org/bugzilla/show_bug.cgi?id=21479](stripping LTO archives)?

**Comment by shermp** [comment]
It seems happy with `-fpic` as well.

The error I was getting from the linker was specifically regarding `-fPIC`

**Comment by shermp** [comment]
Note that the rest of the `SHARED_CFLAGS` don't appear to be required when linking a static build in Go, just `-fpic`.

**Comment by NiLuJe** [comment]
Okay, then `make pic` it is, then ;).

Thanks!
