### ISSUE TITLE
Compilation Issue

### ISSUE THREAD

**Issue by codeeleven0** [NiLuJe/FBInk#75]
**cc** fails at ```gettimeofday(&ev.time, NULL);``` with error ```fbink_button_scan.h:70:41: error: 'struct input_event' has no member named 'time'```. I am using a Kobo Aura Second Edition and it doesn't have any hardware buttons. Is there any way to disable the compilation of this file?

**Comment by codeeleven0** [comment]
Just solved by editing the Makefile.

**Comment by NiLuJe** [comment]
You also appear to be using a really old toolchain (or at least really, really old kernel headers), which might not be a great idea.

c.f., https://github.com/koreader/koxtoolchain

Because, yeah, while, `button_scan` is essentially deprecated here, not being able to deal with `input_event` will be... *problematic* if you ever need to do any kind of input handling ;o).

**Comment by codeeleven0** [comment]
I tried to compile FBInk that comes with fbink-xdamage with the latest Alpine Linux chroot at my Kobo Aura SE. Then I encountered the error. So, I modified some files and it worked!  Then I created a fork of FBInk and modified it for my Kobo Aura SE. After that, I forked fbink-xdamage and added my fork as a submodule. Gonna test it later. Just removed lines that add the button scanner from the Makefile and removed the import from fbink.c. If you add my fork of FBInk for Kobo Aura SE users (https://github.com/codeeleven0/FBInk-AuraSE) to the README file, I'd be really happy.

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________

**Comment by Eeems** [comment]
Any reason you are wanting to add a fork instead of upstreaming the changes behind a flag similar to the `KINDLE`, `LEGACY`, `POCKETBOOK`, `CERVANTES`, and `REMARKABLE` flags?

**Comment by codeeleven0** [comment]
> Any reason you are wanting to add a fork instead of upstreaming the changes behind a flag similar to the `KINDLE`, `LEGACY`, `POCKETBOOK`, `CERVANTES`, and `REMARKABLE` flags?

I want to make things easier.
I am creating an install-script for installing Alpine and a minimal desktop on my Kobo Aura SE. Everytime I try it I don't want to hassle with configs, so I created forks, which'll help me a lot.

**Comment by NiLuJe** [comment]
There's no need to hack around it, the Makefile is already modular (c.f., https://github.com/NiLuJe/FBInk#how-do-i-build-it).

i.e., `make kobo MINIMAL=1` will probably be enough for xdamage, and you'll get a (much) smaller library to boot. (If in doubt, pass DRAW=1, too).

**Comment by codeeleven0** [comment]
But I am compiling FBInk from fbink-xdamage. Because of that I created a fork with some hacks.
________________________________

**Comment by NiLuJe** [comment]
That sure sounds easier than just [updating one line](https://github.com/schuhumi/fbink-xdamage/blob/6fd5e509ec36f901bb937ad78728781d2b16affb/Makefile#L2)...

**Comment by NiLuJe** [comment]
And as far as xdamage is concerned, https://github.com/schuhumi/fbink-xdamage/commit/de2e6de6e532d698ab0e6e73319e4a50b942cfbd may be relevant to your interests ;).

**Comment by codeeleven0** [comment]
I am making a shortcut for an automated script in NickelMenu. So, it would be easier to runvand repos are up to date.
