### ISSUE TITLE
Color Font on the Kobo Clara Colour 

### ISSUE THREAD

**Issue by leogott** [NiLuJe/FBInk#79]
Hejo, I recently got one of the new color ereaders (as they've become quite affordable) and am looking forward to do some tinkering. Maybe port ~~Doom~~ some piece of productivity software

From what I can tell FBInk stable is working, (unlike stable releases of KOReader and Plato :disappointed: ).

It looks like printing text in color is not implemented yet? 

https://github.com/NiLuJe/FBInk/blob/c4cc9b61b739c300eafa30f1beef590e3bd45abc/CLI.md?plain=1#L208-L217

However [one of the example screenshots](https://raw.githubusercontent.com/NiLuJe/FBInk/master/resources/fbink_image.png) shows a color image... haven't tried yet, are color images implemented?

I'd love to have at least RED, YELLOW, GREEN, BLUE available! Is that within the scope of this library?

---

Device: Kobo Clara Colour (But should apply to Kobo Libra Colour as well)
Software: 4.39.22861

Version:Probably 1.25.0 ( whatever was bundled with the all in one. )

**Comment by ericcastro** [comment]
did you get it to work on a new color kobo ?

I have the Libra Colour and I'm getting this error:
`[root@monza root]# fbink -x 1 -y 10 "Hello World!"
[FBInk] Unidentified Kobo device code (390)!
[FBInk] Detected a Kobo Unknown! (390 => ?? @ Mark ?)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 167 dpi
[FBInk] Variable fb info: 1264x1680, 32bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 8494080 bytes & line length: 5056 bytes
[FBInk] Canonical rotation: 2 (Upside Down, 180°)
[FBInk] Fontsize set to 16x16 (IBM base glyph size: 8x8)
[FBInk] Line length: 79 cols, Page size: 105 rows
[FBInk] Horizontal fit is perfect!
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Printing string 'Hello World!' @ column 1 + 0px, row 10 + 0px (overlay: N, no BG: N, no FG: N, inverted: N, flashing: N, centered: N, halfway: N, left padded: N, right padded: N, clear screen: N, waveform: AUTO, dithering: PASSTHROUGH, nightmode: N, skip refresh: N, font: 0, font scaling: x0)
[FBInk] [refresh_kobo] MXCFB_SEND_UPDATE_V1_NTX: Interrupted system call!
[FBInk] [fbink_print] Failed to refresh the screen!
[CLI] Failed to print that string!
[root@monza root]# fbink -x 1 -y 10 "Hello World!"
[FBInk] Unidentified Kobo device code (390)!
[FBInk] Detected a Kobo Unknown! (390 => ?? @ Mark ?)
[FBInk] Clock tick frequency appears to be 100 Hz
[FBInk] Screen density set to 167 dpi
[FBInk] Variable fb info: 1264x1680, 32bpp @ rotation: 1 (Clockwise, 90°)
[FBInk] Fixed fb info: ID is "hwtcon", length of fb mem: 8494080 bytes & line length: 5056 bytes
[FBInk] Canonical rotation: 2 (Upside Down, 180°)
[FBInk] Fontsize set to 16x16 (IBM base glyph size: 8x8)
[FBInk] Line length: 79 cols, Page size: 105 rows
[FBInk] Horizontal fit is perfect!
[FBInk] Pen colors set to #000000 for the foreground and #FFFFFF for the background
Printing string 'Hello World!' @ column 1 + 0px, row 10 + 0px (overlay: N, no BG: N, no FG: N, inverted: N, flashing: N, centered: N, halfway: N, left padded: N, right padded: N, clear screen: N, waveform: AUTO, dithering: PASSTHROUGH, nightmode: N, skip refresh: N, font: 0, font scaling: x0)
[FBInk] [refresh_kobo] MXCFB_SEND_UPDATE_V1_NTX: Interrupted system call!
[FBInk] [fbink_print] Failed to refresh the screen!
[CLI] Failed to print that string!`

which makes me believe fbink has not yet updated to work with them.

hopefully we'll get them supported soon

**Comment by leogott** [comment]
@ericcastro I successfully printed some text at least. Have you tried it while not specifying the location?
```bash
FBINK_BIN="/usr/local/kfmon/bin/fbink"
echo "DONT PANIC" | ${FBINK_BIN} -q -C GRAYA -B BLACK
```
(Kobo Clara Colour)

**Comment by NiLuJe** [comment]
The master branch works just fine on the new devices, has for quite a while now.

As for color font rendering, this *should* be possible for the fixed-cell renderer if you set pen colors manually via `fbink_set_fg_pen_rgba`.

For OpenType, there's currently an optimization in place that uses the alpha coverage mask as-is, so you'd need to enable fgless/bgless/overlay to bypass that optimization, and it *should* work.

Haven't tested any of this, and I don't necessarily intend to work much on that, because I'm thoroughly unenthused about the current color tech, but patches very welcome ;).

And sorry about missing this issue, I currently don't have time to check GH notifications, relying on email notifications instead, and I don't get email notifications for new issues/PRs on repos I own -_-".

(i.e., the ping is what made me notice this).

**Comment by NiLuJe** [comment]
> ```shell
> FBINK_BIN="/usr/local/kfmon/bin/fbink"
> ```

FYI, the KFMon build is extremely minimal, and doesn't support anything other than fixed-cell rendering (e.g., no opentype, no images).

c.f., the very top of `fbink --help`, which always displays the feature set of the binary.

**Comment by NiLuJe** [comment]
And there's now a [build action](https://github.com/NiLuJe/FBInk/actions/workflows/build.yaml) if you need live Kobo binaries.

**Comment by NiLuJe** [comment]
Anti-aliasing might be a bit janky on color OT rendering, FWIW.

**Comment by NiLuJe** [comment]
There, fixed color AA in the OT codepaths. Any remaining jank (e.g., try green on pink) can be laid at the feet of the current tech (check an fbgrab when in doubt).
